In [30]:
pip install pandas

Requirement already satisfied: pandas in c:\users\manuj\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\manuj\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\manuj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\manuj\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\manuj\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\manuj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
#data cleaning using pandas
import pandas as pd
smart_farming_df = pd.read_csv("../raw_data/smart_Farming_Crop_Yield_2024.csv")

In [112]:
#Remove duplicates from smart_farming_df
smart_farming_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   farm_id               500 non-null    object
 1   region                500 non-null    object
 2   crop_type             500 non-null    object
 3   soil_moisture_%       500 non-null    float64
 4   soil_pH               500 non-null    float64
 5   temperature_C         500 non-null    float64
 6   rainfall_mm           500 non-null    float64
 7   humidity_%            500 non-null    float64
 8   sunlight_hours        500 non-null    float64
 9   irrigation_type       350 non-null    object
 10  fertilizer_type       500 non-null    object
 11  pesticide_usage_ml    500 non-null    float64
 12  sowing_date           500 non-null    object
 13  harvest_date          500 non-null    object
 14  total_days            500 non-null    int64
 15  yield_kg_per_hectare  500 non-null    float64
 16  sensor_id             500 non-null    object
 17  timestamp             500 non-null    object
 18  latitude              500 non-null    float64
 19  longitude             500 non-null    float64
 20  NDVI_index            500 non-null    float64
 21  crop_disease_status   370 non-null    object
dtypes: float64(11), int64(1), object(10)
memory usage: 86.1+ KB

In [4]:
smart_farming_df = smart_farming_df.drop_duplicates()

In [5]:
smart_farming_df.isnull().sum()

farm_id                   0
region                    0
crop_type                 0
soil_moisture_%           0
soil_pH                   0
temperature_C             0
rainfall_mm               0
humidity_%                0
sunlight_hours            0
irrigation_type         150
fertilizer_type           0
pesticide_usage_ml        0
sowing_date               0
harvest_date              0
total_days                0
yield_kg_per_hectare      0
sensor_id                 0
timestamp                 0
latitude                  0
longitude                 0
NDVI_index                0
crop_disease_status     130
dtype: int64

In [115]:
smart_farming_df['irrigation_type'] = smart_farming_df['irrigation_type'].fillna('Unknown')

In [6]:
smart_farming_df.isnull().sum()

farm_id                   0
region                    0
crop_type                 0
soil_moisture_%           0
soil_pH                   0
temperature_C             0
rainfall_mm               0
humidity_%                0
sunlight_hours            0
irrigation_type         150
fertilizer_type           0
pesticide_usage_ml        0
sowing_date               0
harvest_date              0
total_days                0
yield_kg_per_hectare      0
sensor_id                 0
timestamp                 0
latitude                  0
longitude                 0
NDVI_index                0
crop_disease_status     130
dtype: int64

In [7]:
smart_farming_df['crop_disease_status'] = smart_farming_df['crop_disease_status'].fillna('None')

In [8]:
smart_farming_df['sowing_date'] = pd.to_datetime(smart_farming_df['sowing_date'])

In [9]:
smart_farming_df['harvest_date'] = pd.to_datetime(smart_farming_df['harvest_date'])

In [10]:
smart_farming_df['timestamp'] = pd.to_datetime(smart_farming_df['timestamp'])

In [11]:
smart_farming_df['crop_type'].unique()

array(['Wheat', 'Soybean', 'Maize', 'Cotton', 'Rice'], dtype=object)

In [12]:
smart_farming_df['irrigation_type'].unique()
smart_farming_df['crop_type'].unique()
smart_farming_df['sensor_id'].unique()
smart_farming_df['region'].unique()
smart_farming_df['fertilizer_type'].unique() 
smart_farming_df['irrigation_type'].unique()
smart_farming_df['crop_disease_status'].unique()

array(['Mild', 'None', 'Severe', 'Moderate'], dtype=object)

In [15]:
#Save cleaned data of samrt_farming_df into cleaned data folder 
#Handle Missing Values(drop and filled)
#Correct Data Types(date)
#Dropped Irrelevant Columns 
#checked unique values

smart_farming_df.to_csv("../cleaned_data/cleaned_smart_farming_df_new.csv", index=False)

In [16]:
smart_farming_df.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,sowing_date,harvest_date,total_days,yield_kg_per_hectare,timestamp,latitude,longitude,NDVI_index
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500,500,500.000000,500.00000,500,500.000000,500.000000,500.000000
mean,26.750140,6.523980,24.675740,181.685740,65.194460,7.03014,26.586980,2024-02-15 05:42:43.199999744,2024-06-13 17:36:57.599999744,119.496000,4032.92694,2024-04-14 17:42:43.200000256,22.442473,80.392248,0.602060
min,10.160000,5.510000,15.000000,50.170000,40.230000,4.01000,5.050000,2024-01-01 00:00:00,2024-04-09 00:00:00,90.000000,2023.56000,2024-01-03 00:00:00,10.004243,70.020021,0.300000
25%,17.890000,6.030000,20.295000,119.217500,51.865000,5.66750,14.945000,2024-01-23 00:00:00,2024-05-24 00:00:00,105.750000,2994.82000,2024-03-12 00:00:00,16.263202,75.374713,0.447500
50%,25.855000,6.530000,24.655000,191.545000,65.685000,6.99500,25.980000,2024-02-16 00:00:00,2024-06-14 00:00:00,119.000000,4071.69000,2024-04-14 00:00:00,21.981743,80.650284,0.610000
75%,36.022500,7.040000,29.090000,239.035000,77.995000,8.47000,38.005000,2024-03-09 00:00:00,2024-07-06 06:00:00,134.000000,5062.11000,2024-05-18 06:00:00,28.528948,85.654629,0.750000
max,44.980000,7.500000,34.840000,298.960000,90.000000,10.00000,49.940000,2024-03-28 00:00:00,2024-08-17 00:00:00,150.000000,5998.29000,2024-08-12 00:00:00,34.981531,89.991901,0.900000
std,10.150053,0.585558,5.348899,72.293091,14.642849,1.69167,13.202429,NaN,NaN,16.798046,1174.43304,NaN,7.283492,5.910664,0.175402

In [17]:
smart_farming_df['irrigation_type'].unique()

array([nan, 'Sprinkler', 'Drip', 'Manual'], dtype=object)

In [19]:
smart_farming_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   farm_id               500 non-null    object
 1   region                500 non-null    object
 2   crop_type             500 non-null    object
 3   soil_moisture_%       500 non-null    float64
 4   soil_pH               500 non-null    float64
 5   temperature_C         500 non-null    float64
 6   rainfall_mm           500 non-null    float64
 7   humidity_%            500 non-null    float64
 8   sunlight_hours        500 non-null    float64
 9   irrigation_type       350 non-null    object
 10  fertilizer_type       500 non-null    object
 11  pesticide_usage_ml    500 non-null    float64
 12  sowing_date           500 non-null    datetime64[ns]
 13  harvest_date          500 non-null    datetime64[ns]
 14  total_days            500 non-null    int64
 15  yield_kg_per_hectare  500 non-null    float64
 16  sensor_id             500 non-null    object
 17  timestamp             500 non-null    datetime64[ns]
 18  latitude              500 non-null    float64
 19  longitude             500 non-null    float64
 20  NDVI_index            500 non-null    float64
 21  crop_disease_status   500 non-null    object
dtypes: datetime64[ns](3), float64(11), int64(1), object(7)
memory usage: 86.1+ KB

In [21]:
#Clean data from crop_recommendation_multiregion file

crop_rec_df  = pd.read_csv("../raw_data/crop_recommendation_multiregion.csv")

In [22]:
crop_rec_df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
soil_pH        0
rainfall       0
label          0
region         0
dtype: int64

In [87]:
crop_rec_df.drop_duplicates()

,N,P,K,temperature,humidity,soil_pH,rainfall,label,region
0,13,72,55,19.433552,65.810979,6.184301,119.538242,soybean,Central USA
1,111,38,47,24.300279,68.632237,6.076756,185.183212,rice,Central USA
2,104,52,50,16.426005,51.493164,6.557569,55.992183,wheat,Central USA
3,71,48,32,18.896752,60.420200,6.402489,102.837561,maize,East Africa
4,75,57,53,17.040503,70.807264,6.844746,96.792116,wheat,South USA
...,...,...,...,...,...,...,...,...,...
2495,111,52,48,28.306822,90.295578,6.050181,160.118687,rice,South USA
2496,97,45,50,14.987781,59.669923,6.462411,38.731778,wheat,Central USA
2497,114,60,53,27.355508,72.296978,6.000893,181.760688,rice,Central USA
2498,117,75,59,22.112659,68.205133,6.063577,130.039831,maize,Central USA
2499,107,51,52,28.312196,62.457913,6.834974,91.072739,cotton,South India

In [23]:
crop_rec_df['region'].unique()

array(['Central USA', 'East Africa', 'South USA', 'South India',
       'North India'], dtype=object)

In [24]:
crop_rec_df['label'].unique()

array(['soybean', 'rice', 'wheat', 'maize', 'cotton'], dtype=object)

In [25]:
crop_rec_df['label'] = crop_rec_df['label'].str.capitalize()  # soybean → Soybean

In [27]:
crop_rec_df.to_csv("../cleaned_data/cleaned_crop_rec_df.csv", index=False)

In [135]:
crop_rec_df

,N,P,K,temperature,humidity,soil_pH,rainfall,label,region
0,13,72,55,19.433552,65.810979,6.184301,119.538242,Soybean,Central USA
1,111,38,47,24.300279,68.632237,6.076756,185.183212,Rice,Central USA
2,104,52,50,16.426005,51.493164,6.557569,55.992183,Wheat,Central USA
3,71,48,32,18.896752,60.420200,6.402489,102.837561,Maize,East Africa
4,75,57,53,17.040503,70.807264,6.844746,96.792116,Wheat,South USA
...,...,...,...,...,...,...,...,...,...
2495,111,52,48,28.306822,90.295578,6.050181,160.118687,Rice,South USA
2496,97,45,50,14.987781,59.669923,6.462411,38.731778,Wheat,Central USA
2497,114,60,53,27.355508,72.296978,6.000893,181.760688,Rice,Central USA
2498,117,75,59,22.112659,68.205133,6.063577,130.039831,Maize,Central USA
2499,107,51,52,28.312196,62.457913,6.834974,91.072739,Cotton,South India